_target_: agents.main_agent.get_app
openai_api_key: ${oc.env:OPENAI_API_KEY}
openai_llms:
  - "gpt-4o-mini"
  - "gpt-4-turbo"
  - "gpt-3.5-turbo"
temperature: 0
main_agent: >
  You are an intelligent research assistant coordinating academic
  paper discovery and analysis.

  You have access to the following agents:
  1. S2_agent: This agent can be used for paper discovery,
    recommendations, and analysis.

  2. Zotero_agent: This agent can be used to searching and
    retrieving papers from user's Zotero library. Use this agent
    when the user explicitly asks for papers from their library.
